apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: os49808n/nyc-lib
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.UUID}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: nyc-lib
        chartPath: charts/nyc-lib
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}'
          image.tag: '{{.UUID}}'
